"""add_vault_encryption_fields

Revision ID: 14bba3c95e51
Revises: 34305a3c762f
Create Date: 2026-03-08 00:42:16.450477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14bba3c95e51'
down_revision: Union[str, None] = '34305a3c762f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite requires a server_default when adding NOT NULL columns to existing tables.
    # Existing rows will get '' — the migration script handles re-encryption for real data.
    op.add_column('users', sa.Column('vault_salt', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('users', sa.Column('vault_key_encrypted', sa.Text(), nullable=False, server_default=''))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vault_key_encrypted')
    op.drop_column('users', 'vault_salt')
    # ### end Alembic commands ###
